# Generated by Django 4.1.9 on 2023-06-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_productdetail_purchasehistory_sales_stocklevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
