# Generated by Django 4.1.9 on 2023-07-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_invoices_sales_sale_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='customer_contact_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
