# Generated by Django 4.1.9 on 2023-07-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0008_alter_invoices_invoice_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSalePayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.invoices')),
            ],
        ),
    ]
